#!/usr/bin/env python3
"""InterviewLoop · 生成零安装单文件提示词
用法：python3 scripts/build_prompt.py
输出：PROMPT.zh.md、PROMPT.en.md（协议 + 分类库 + 两个模板合成一个文件，可作为附件上传到任意大模型聊天应用）
协议或分类库改动后重新运行本脚本；不要手改生成文件。
"""
import os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rd=lambda p: open(os.path.join(ROOT,p),encoding='utf-8').read().strip()
TAX=['interviewer-types','skeletons','signals','pitfalls','stages']
HEAD_ZH='''# InterviewLoop · 单文件提示词（零安装）

> 本文件由 scripts/build_prompt.py 生成，内容 = PROTOCOL.md + taxonomy/cn 五个文件 + 两个模板。不要手改。
> 仓库：https://github.com/interviewloop-cn/interviewloop

## 给使用者：怎么用

不用装任何东西，也不用 API key。把**本文件作为附件**上传到你常用的大模型聊天应用（Kimi、DeepSeek、豆包、通义千问、智谱、ChatGPT、Claude 都可以；不支持附件就整段粘贴），然后发一句话：

- 面试前：`运行模块 A。下面是 JD 全文和我的简历要点：……`（两样都必须给）
- 想出声练：模块 A 输出之后说 `开始预演`
- 面试后：`运行模块 B。下面是我的面后笔记：……`（笔记模板在本文件末尾；填不全也行，模型只问缺的）
- 结果出来：`运行模块 C。结果：通过 / 未通过 / 走到第 N 轮 / 未知`

你的个人手册：第一次没有就不用给。之后每次把模型输出末尾的"手册增量"贴进你自己的 handbook.md（模板在本文件末尾），下一次连同手册一起发给模型。手册只在你自己手里。

这不是 AI 面试官，也不会替你写答案。只有你能填的位置会留空并标 `【空位·思考漏洞】`，那是留给你想的。

## 给模型：怎么执行

你正在运行 InterviewLoop 协议。下面依次是协议全文、分类库五个文件、两个模板。严格按协议对应模块的输出顺序与结构输出，不增删段落；分类库缺失时按协议 0.3 处理；不联网查公司、岗位、薪资。
'''
HEAD_EN='''# InterviewLoop · Single-file prompt (no install)

> Generated by scripts/build_prompt.py: PROTOCOL.en.md + the five taxonomy/en files + two templates. Do not edit by hand. The Chinese files are authoritative.
> Repository: https://github.com/interviewloop-cn/interviewloop

## For you: how to use it

No install, no API key. Upload **this file as an attachment** to the chat app you already use (ChatGPT, Claude, Gemini, DeepSeek, Kimi…; paste it if attachments are not supported), then send one line:

- Before an interview: `Run Module A. Here is the full JD and my résumé points: …` (both are required)
- To practise out loud: after Module A's output say `start rehearsal`
- After an interview: `Run Module B. Here are my post-interview notes: …` (template at the end of this file; incomplete is fine, the model asks only for what is missing)
- When the result arrives: `Run Module C. Result: pass / fail / reached round N / unknown`

Your personal handbook: none needed the first time. After each run paste the "handbook increment" at the end of the output into your own handbook.md (template at the end of this file) and send the handbook along next time. It stays with you.

This is not an AI interviewer and it will not write answers for you. Places only you can fill are left blank and marked `【Blank · Thinking Gap】`.

## For the model: how to run

You are running the InterviewLoop protocol. Below are the full protocol, the five taxonomy files and two templates. Follow the output order and structure of the requested module exactly; do not add or drop sections; if the taxonomy is missing follow protocol 0.3; do not browse for companies, roles or salaries.
'''
def build(lang):
    if lang=='zh': head,proto,tax,tpl=HEAD_ZH,'PROTOCOL.md','taxonomy/cn','templates/zh'
    else: head,proto,tax,tpl=HEAD_EN,'PROTOCOL.en.md','taxonomy/en','templates/en'
    parts=[head,'\n---\n\n===== '+proto+' =====\n\n'+rd(proto)]
    for t in TAX: parts.append(f'\n---\n\n===== {tax}/{t}.md =====\n\n'+rd(f'{tax}/{t}.md'))
    for t in ['post-interview-notes','handbook']: parts.append(f'\n---\n\n===== {tpl}/{t}.md =====\n\n'+rd(f'{tpl}/{t}.md'))
    out='\n'.join(parts)+'\n'
    name=f'PROMPT.{lang}.md'; open(os.path.join(ROOT,name),'w',encoding='utf-8').write(out)
    print(name,len(out.encode('utf-8'))//1024,'KB,',len(out),'字符')
if __name__=='__main__':
    build('zh'); build('en')
